<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LM-SFA-11021114" ignored="0" name="test" tests="3" failures="1" timestamp="2021-10-27T15:57:47 PDT" time="0.218" errors="0">
  <testcase name="test1" time="0.101" classname="testngdemos.TestngRetryDemo"/>
  <testcase name="test2" time="0.005" classname="testngdemos.TestngRetryDemo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testngdemos.TestngRetryDemo.test2(TestngRetryDemo.java:16)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.002" classname="testngdemos.TestngRetryDemo"/>
</testsuite> <!-- test -->
